const chunkArray = require('../src/array/chunkArray'); 

describe("Array|chunkArray", () => {
  // 세팅한 숫자로 배열안에 적용한 갯수의 배열로 생성된다. ex) chunkArray(1, [1 ,2]) => [[1], [2]]
  test('The set number is generated by the number applied to the array.', () => {
    expect(chunkArray([1, 2, 3, 4, 5], 1)).toEqual([[1],[2],[3],[4],[5]]);
    expect(chunkArray([1, 2, 3, 4, 5], 2)).toEqual([[1,2], [3,4], [5]]); 
    expect(chunkArray([1, 2, 3, 4, 5], 3)).toEqual([[1,2,3], [4,5]]); 
  });
});


